### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by tuanteku9x** [Widiskel/aytu-fi-testnet-bot#1]
I see it shows confirmed but the Leader Board does not record the score.
I tried swapping manually, and it scored for me

**Comment by Widiskel** [comment]
still working on me, did you pull new update already ?

**Comment by tuanteku9x** [comment]
> still working on me, did you pull new update already ?

Trying update your code now...
update: it's working now :(

**Comment by tuanteku9x** [comment]
I don't now why, but it's not add points for tradding on dasboard now... again.
I've upadate your code again, and it's not working pro

**Comment by Widiskel** [comment]
i think there problem with aytu-fi it self, i try to do manual swap and it always failed. tx send to explorer but the transaction processing always end up with failed and try again. even if im adjust the slippage to 20%. i think we just need to wait. i will update the bot as soon as posible if any change needed

**Comment by tuanteku9x** [comment]
But i see swap configmed....

**Comment by Widiskel** [comment]
try to pull

**Comment by tuanteku9x** [comment]
> try to pull

it's working fine now pro :D
