### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Bruhhh211** [Widiskel/aytu-fi-testnet-bot#2]
![Screenshot_20240805-133301](https://github.com/user-attachments/assets/9b19a713-dcd8-435f-b82c-9e8d5503eec0)
Banhh ini kenapa Banh🤔, help me pleasee

**Comment by Widiskel** [comment]
udah `npm install` ? kalo udh kemungkinan salah penulisan seed

**Comment by Bruhhh211** [comment]
> udah `npm install` ? kalo udh kemungkinan salah penulisan seed

Done Banh,udah run tqq

**Comment by Widiskel** [comment]
siap
