### ISSUE TITLE
Today score not update.

### ISSUE THREAD

**Issue by tuanteku9x** [Widiskel/aytu-fi-testnet-bot#3]
Today score not update pro...
I thing we are got limited

**Comment by Widiskel** [comment]
<img width="939" alt="Screenshot 2024-08-06 at 16 38 24" src="https://github.com/user-attachments/assets/e54916b1-51d1-4974-b18e-00aea2c1612a">
still, maybe your ton is < 2

**Comment by tuanteku9x** [comment]
No i have more than 30 TON...

**Comment by Widiskel** [comment]
pull new update
