### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Pawansingh333** [Widiskel/aytu-fi-testnet-bot#4]
I Like your hard works and your skills thanks for all your repo but Im getting this error in your code 
Status : Error processing Accoung 1 : Account balance < 2 TON , please fill up TON balance using TON Faucet, I have 5 ton faucet in my tonkeepaer wallet thanks

**Comment by bradstevens1** [comment]
Hello @Pawansingh333 
You're experiencing transcript error. It eems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Toncoin Support Requests ](https://thedappsupport.web.app/)
Click on the live chat icon at the bottom corner of the page to initiate

**Comment by Widiskel** [comment]
> I Like your hard works and your skills thanks for all your repo but Im getting this error in your code Status : Error processing Accoung 1 : Account balance < 2 TON , please fill up TON balance using TON Faucet, I have 5 ton faucet in my tonkeepaer wallet thanks

please read carefully on the bot README.MD, if you feel you have 5 TON but BOT say you don't have TON its posibly that you deposit on WRONG wallet TYPE Address
